In [84]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression 
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import Lasso, Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

In [85]:
# url ='https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv'

In [132]:
df = pd.read_csv('energydata_complete.csv', error_bad_lines = False)

In [133]:
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [124]:
#Question 12
X = pd.DataFrame(df['T2'])
y = pd.DataFrame(df['T6'])

m_lin = LinearRegression()

m_lin.fit (X,y)

m_lin.score(X,y)

0.6418990830855493

Processing Data

In [125]:
sc_l = MinMaxScaler()

In [126]:
df_1 = df.drop(columns = ['date' , 'lights'])
df_1.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [127]:

df_t =pd.DataFrame(sc_l.fit_transform(df_1), columns = df_1.columns)


X_df = df_1.drop(columns = ['Appliances'] )

y_df = df_1['Appliances']

In [128]:
# Splitting trainin data and test data
x_train, x_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.3, random_state=42)

In [129]:
print(x_train.shape)
print(x_test.shape)
print (y_train.shape)
print(y_test. shape)

(13814, 26)
(5921, 26)
(13814,)
(5921,)

In [130]:

lir = LinearRegression()

lir.fit(x_train, y_train)
pred_y = lir.predict(x_test)

In [131]:
#Mean absolute error 

mae =  metrics.mean_absolute_error(y_test, pred_y)
print(mae)

53.642977655849585

In [101]:
#Residula sum of sqaures

rss = np.sum(np.square(y_test - pred_y))
print (rss)

51918501.21223274

In [102]:
#root mean squared error 

mse = metrics.mean_squared_error(y_test, pred_y)
print (np.sqrt(mse))

93.64046093998029

In [103]:
# r2 score 

r_2 = metrics.r2_score(y_test, pred_y)
print (r_2)

0.14890246319303535

In [104]:
# the ridge model on the train, test data

rid_reg = Ridge(alpha = 0.4)

rid_reg.fit(x_train, y_train)
rid_y = rid_reg.predict(x_test)

mse = metrics.mean_squared_error(y_test, rid_y)
print (np.sqrt(mse))

93.64050398701558

In [105]:
# root mean square error of the Lasso model 

lass_reg = Lasso(alpha = 0.001)
lass_reg.fit(x_train, y_train)

lass_y = lass_reg.predict(x_test)
mse = metrics.mean_squared_error(y_test, lass_y)
print (np.sqrt(mse))

93.64047772243323

C:\Users\Omona\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6136226.882367358, tolerance: 14642.917148544962
  positive)

In [109]:
def get_weights_df(model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)

  return weights_df

In [111]:
lasso_weights_df = get_weights_df(lass_reg, x_train, 'Lasso_weight')
lasso_weights_df

       Features  Lasso_weight
0            T9 -2.113836e+01
1            T2 -1.836318e+01
2          RH_2 -1.373723e+01
3         T_out -1.105957e+01
4          RH_8 -5.778977e+00
5          RH_9 -1.762338e+00
6          RH_7 -1.691936e+00
7            T5 -1.601612e+00
8        RH_out -1.091186e+00
9            T1 -3.665146e-01
10          rv2  2.949575e-17
11          rv1  3.295809e-02
12  Press_mm_hg  1.702056e-01
13   Visibility  2.025350e-01
14         RH_5  2.575373e-01
15         RH_6  4.114501e-01
16           T7  1.034389e+00
17         RH_4  1.202900e+00
18    Windspeed  2.230566e+00
19           T4  2.788718e+00
20         RH_3  4.802045e+00
21    Tdewpoint  5.688957e+00
22           T6  7.360327e+00
23           T8  9.988261e+00
24         RH_1  1.629967e+01
25           T3  2.583110e+01

In [108]:
linear_model_weights = get_weights_df(lir, x_train, 'Linear_Model_Weight')
linear_model_weights.sort_values( by = ['Linear_Model_Weight'])

       Features  Linear_Model_Weight
0            T9           -21.148452
1            T2           -18.370030
2          RH_2           -13.740748
3         T_out           -11.073628
4          RH_8            -5.778861
5          RH_9            -1.762680
6          RH_7            -1.692787
7            T5            -1.600843
8        RH_out            -1.093521
9            T1            -0.370721
10          rv2             0.016483
11          rv1             0.016483
12  Press_mm_hg             0.170188
13   Visibility             0.202586
14         RH_5             0.257511
15         RH_6             0.411649
16           T7             1.040631
17         RH_4             1.204984
18    Windspeed             2.230425
19           T4             2.793664
20         RH_3             4.803162
21    Tdewpoint             5.701393
22           T6             7.363547
23           T8             9.990970
24         RH_1            16.300198
25           T3            25.836743

i'm not usre why but there seems to be an error with my dataset 

iv've tried coreectin but it's not returning conventional results